name: Test build

on:
  pull_request:
    branches: [master, develop]

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Build Docs
        run: |
          npm ci
          npm run build
